# Generated by Django 4.2.7 on 2025-08-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True, verbose_name='세션 ID')),
                ('filename', models.CharField(max_length=255, verbose_name='파일명')),
                ('total_size', models.BigIntegerField(verbose_name='총 크기 (bytes)')),
                ('uploaded_size', models.BigIntegerField(default=0, verbose_name='업로드된 크기 (bytes)')),
                ('chunk_size', models.IntegerField(default=1048576, verbose_name='청크 크기 (bytes)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('expires_at', models.DateTimeField(verbose_name='만료일시')),
            ],
            options={
                'verbose_name': '파일 업로드 세션',
                'verbose_name_plural': '파일 업로드 세션들',
                'db_table': 'file_upload_sessions',
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('stored_filename', models.CharField(max_length=255, unique=True, verbose_name='저장된 파일명')),
                ('file_type', models.CharField(choices=[('image', '이미지'), ('pdf', 'PDF')], max_length=10, verbose_name='파일 유형')),
                ('file_size_mb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='파일 크기 (MB)')),
                ('file_hash', models.CharField(blank=True, max_length=64, unique=True, verbose_name='파일 해시')),
                ('storage_path', models.CharField(max_length=500, verbose_name='저장 경로')),
                ('upload_status', models.CharField(choices=[('uploading', '업로드 중'), ('completed', '완료'), ('failed', '실패')], default='uploading', max_length=20, verbose_name='업로드 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '원본 파일',
                'verbose_name_plural': '원본 파일들',
                'db_table': 'source_files',
            },
        ),
    ]
