# Generated by Django 4.2.7 on 2025-08-10 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='fileuploadsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='sourcefile',
            index=models.Index(fields=['user', 'created_at'], name='source_file_user_id_7f9684_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcefile',
            index=models.Index(fields=['file_hash'], name='source_file_file_ha_5ee32e_idx'),
        ),
        migrations.AddIndex(
            model_name='fileuploadsession',
            index=models.Index(fields=['user', 'created_at'], name='file_upload_user_id_6da4c1_idx'),
        ),
        migrations.AddIndex(
            model_name='fileuploadsession',
            index=models.Index(fields=['session_id'], name='file_upload_session_68c0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='fileuploadsession',
            index=models.Index(fields=['expires_at'], name='file_upload_expires_e6ef1d_idx'),
        ),
    ]
