# -*- coding: utf-8 -*-
"""8.4worksheet_analysis_gradio_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wj2-UdW9uJzp-ON6vuxseGLJHsiCNk_s

# 📚 학습지 분석 시스템 Gradio 데모

**시각 장애 아동을 위한 AI 기반 학습지 분석 및 텍스트 변환 시스템**

## 시스템 구성
- **LAM (Layout Analysis Module)**: DocLayout-YOLO를 사용한 레이아웃 분석
- **TSPM (Text & Scene Processing Module)**: Tesseract OCR + OpenAI Vision API
- **CIM (Content Integration Module)**: 결과 통합 및 시각화

## 주요 기능
1. 🎯 학습지 레이아웃 자동 분석
2. 📝 텍스트 영역 OCR 처리
3. 🖼️ 그림/표 AI 설명 생성
4. 📄 접근 가능한 문서 형태로 변환

## 1. 필요한 패키지 설치
"""

# 기본 라이브러리 설치
!pip install -q gradio numpy opencv-python matplotlib pillow tqdm loguru rich
!pip install -q pytesseract requests transformers openai huggingface-hub

# 시스템 패키지 설치
!apt-get update -q
!apt-get install -q -y tesseract-ocr tesseract-ocr-kor fonts-nanum

print("✅ 기본 패키지 설치 완료!")

# DocLayout-YOLO 설치
import os
import sys

# 현재 디렉토리 확인
current_dir = os.getcwd()
print(f"현재 작업 디렉토리: {current_dir}")

# DocLayout-YOLO가 이미 설치되어 있는지 확인
if not os.path.exists('DocLayout-YOLO'):
    print("DocLayout-YOLO 다운로드 중...")
    !git clone https://github.com/opendatalab/DocLayout-YOLO.git

    # DocLayout-YOLO 디렉토리로 이동하여 설치
    os.chdir('DocLayout-YOLO')
    !pip install -q -e .

    # 원래 디렉토리로 복귀
    os.chdir(current_dir)
    print("✅ DocLayout-YOLO 설치 완료!")
else:
    print("✅ DocLayout-YOLO 이미 설치됨!")

# Python 경로에 DocLayout-YOLO 추가
doclayout_path = os.path.join(current_dir, 'DocLayout-YOLO')
if doclayout_path not in sys.path:
    sys.path.append(doclayout_path)

"""## 2. 라이브러리 임포트 및 설정"""

# 필요한 라이브러리 임포트
import gradio as gr
import cv2
import numpy as np
import matplotlib.pyplot as plt
import json
import torch
import time
import base64
import io
import sys
import colorsys
import random
import textwrap
import re
from collections import Counter
from PIL import Image, ImageDraw, ImageFont
from huggingface_hub import hf_hub_download
import pytesseract
import openai
from loguru import logger

# DocLayout-YOLO 임포트
try:
    from doclayout_yolo import YOLOv10
    print("✅ DocLayout-YOLO 임포트 성공!")
except ImportError as e:
    print(f"❌ DocLayout-YOLO 임포트 실패: {e}")
    print("다시 설치를 시도하세요.")

# 로그 설정
logger.remove()
logger.add(sys.stderr, level="INFO")

# 디바이스 설정
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
print(f"✅ 사용 디바이스: {device}")

print("✅ 모든 라이브러리 임포트 완료!")

"""## 3. 워크시트 분석기 클래스 정의"""

class WorksheetAnalyzer:
    def __init__(self):
        self.model = None
        self.device = device
        self.layout_info = []
        self.ocr_results = []
        self.api_results = []

    def download_model(self, model_choice="docstructbench"):
        """사전 훈련된 DocLayout-YOLO 모델 다운로드"""
        models = {
            "doclaynet_docsynth": {
                "repo_id": "juliozhao/DocLayout-YOLO-DocLayNet-Docsynth300K_pretrained",
                "filename": "doclayout_yolo_doclaynet_imgsz1120_docsynth_pretrain.pt"
            },
            "docstructbench": {
                "repo_id": "juliozhao/DocLayout-YOLO-DocStructBench",
                "filename": "doclayout_yolo_docstructbench_imgsz1024.pt"
            },
            "docsynth300k": {
                "repo_id": "juliozhao/DocLayout-YOLO-DocSynth300K-pretrain",
                "filename": "doclayout_yolo_docsynth300k_imgsz1600.pt"
            },
            "SmartEyeSsen": {
                "repo_id": "AkJeond/SmartEyeSsen",
                "filename": "best_tuned_model.pt"
            }
        }

        selected_model = models.get(model_choice, models["docstructbench"])

        try:
            logger.info(f"모델 다운로드 중: {selected_model['repo_id']}")
            filepath = hf_hub_download(
                repo_id=selected_model["repo_id"],
                filename=selected_model["filename"]
            )
            logger.info(f"모델 다운로드 완료: {filepath}")
            return filepath
        except Exception as e:
            logger.error(f"모델 다운로드 실패: {e}")
            raise

    def load_model(self, model_path):
        """DocLayout-YOLO 모델 로드"""
        try:
            logger.info("모델 로드 중...")
            self.model = YOLOv10(model_path, task='predict')
            self.model.to(self.device)
            if hasattr(self.model, 'training'):
                self.model.training = False
            logger.info("모델 로드 완료!")
            return True
        except Exception as e:
            logger.error(f"모델 로드 실패: {e}")
            return False

print("✅ WorksheetAnalyzer 클래스 정의 완료!")

# WorksheetAnalyzer 클래스 메서드 추가 (레이아웃 분석)
def analyze_layout(self, image, model_choice="SmartEyeSsen"):
    """레이아웃 분석"""
    try:
        logger.info("레이아웃 분석 시작...")

        # 임시 이미지 저장
        temp_path = "temp_image.jpg"
        cv2.imwrite(temp_path, image)

        # 모델 설정
        if model_choice == "SmartEyeSsen":
            imgsz = 1024
            conf = 0.25
        elif model_choice == "docsynth300k":
            imgsz = 1600
            conf = 0.15
        else:  # doclaynet_docsynth
            imgsz = 1024
            conf = 0.25

        # 분석 실행
        results = self.model.predict(
            temp_path,
            imgsz=imgsz,
            conf=conf,
            iou=0.45,
            device=self.device
        )

        # 결과 추출
        boxes = results[0].boxes.xyxy.cpu().numpy()
        classes = results[0].boxes.cls.cpu().numpy()
        confs = results[0].boxes.conf.cpu().numpy()
        class_names = self.model.names

        layout_info = []
        for i, (box, cls, conf) in enumerate(zip(boxes, classes, confs)):
            x1, y1, x2, y2 = map(int, box)
            cls_id = int(cls)

            try:
                cls_name = class_names[cls_id]
            except IndexError:
                cls_name = f"unknown_{cls_id}"

            area = (x2 - x1) * (y2 - y1)
            if area < 100:  # 너무 작은 영역 제외
                continue

            layout_info.append({
                'id': i,
                'class_name': cls_name,
                'confidence': float(conf),
                'box': [int(x1), int(y1), int(x2), int(y2)],
                'width': int(x2 - x1),
                'height': int(y2 - y1),
                'area': area
            })

        self.layout_info = layout_info
        logger.info(f"레이아웃 분석 완료: {len(layout_info)}개 영역 감지")
        return layout_info

    except Exception as e:
        logger.error(f"레이아웃 분석 실패: {e}")
        return []

# 메서드를 클래스에 바인딩
WorksheetAnalyzer.analyze_layout = analyze_layout

print("✅ 레이아웃 분석 메서드 추가 완료!")

# WorksheetAnalyzer 클래스 메서드 추가 (OCR 처리)
def perform_ocr(self, image):
    """OCR 처리"""
    target_classes = [
        'title', 'plain text', 'abandon text',
        'table caption', 'table footnote',
        'isolated formula', 'formula caption', 'question type',
        'question text', 'question number'
    ]

    ocr_results = []
    custom_config = r'--oem 3 --psm 6'

    logger.info("OCR 처리 시작...")

    for layout in self.layout_info:
        cls_name = layout['class_name'].lower()
        if cls_name not in target_classes:
            continue

        x1, y1, x2, y2 = layout['box']
        x1 = max(0, x1)
        y1 = max(0, y1)
        x2 = min(image.shape[1], x2)
        y2 = min(image.shape[0], y2)

        cropped_img = image[y1:y2, x1:x2]

        try:
            pil_img = Image.fromarray(cropped_img)
            text = pytesseract.image_to_string(
                pil_img,
                lang='kor+eng',
                config=custom_config
            ).strip()

            if len(text) > 1:
                ocr_results.append({
                    'id': layout['id'],
                    'class_name': cls_name,
                    'coordinates': [x1, y1, x2, y2],
                    'text': text
                })
                logger.info(f"OCR 완료: ID {layout['id']} - {len(text)}자")

        except Exception as e:
            logger.error(f"OCR 실패: ID {layout['id']} - {e}")

    self.ocr_results = ocr_results
    logger.info(f"OCR 처리 완료: {len(ocr_results)}개 텍스트 블록")
    return ocr_results

# 메서드를 클래스에 바인딩
WorksheetAnalyzer.perform_ocr = perform_ocr

print("✅ OCR 처리 메서드 추가 완료!")

# WorksheetAnalyzer 클래스 메서드 추가 (OpenAI API)
def call_openai_api(self, image, api_key):
    """OpenAI Vision API 호출"""
    if not api_key:
        logger.warning("API 키가 제공되지 않아 AI 설명을 건너뜁니다.")
        return []

    target_classes = ['figure', 'table']
    api_results = []

    try:
        client = openai.OpenAI(api_key=api_key)
        logger.info("OpenAI API 처리 시작...")
    except Exception as e:
        logger.error(f"OpenAI 클라이언트 초기화 실패: {e}")
        return []

    prompts = {
        'figure': "이 그림(figure)의 내용을 간단히 요약해 주세요.",
        'table': "이 표(table)의 주요 내용을 요약해 주세요."
    }

    system_prompt = """당신은 시각 장애 아동을 위한 학습 AI 비서입니다.
시각 자료의 내용을 한국어로 간결하고 명확하게 설명해주세요.
설명은 음성으로 변환될 수 있도록 직접적이고 이해하기 쉽게 작성해주세요."""

    for layout in self.layout_info:
        cls_name = layout['class_name'].lower()
        if cls_name not in target_classes:
            continue

        x1, y1, x2, y2 = layout['box']
        cropped_img = image[y1:y2, x1:x2]

        # 이미지를 base64로 인코딩
        pil_img = Image.fromarray(cv2.cvtColor(cropped_img, cv2.COLOR_BGR2RGB))
        buffered = io.BytesIO()
        pil_img.save(buffered, format="PNG")
        img_base64 = base64.b64encode(buffered.getvalue()).decode("utf-8")

        prompt = prompts.get(cls_name, f"이 {cls_name}의 내용을 간단히 설명해 주세요.")

        try:
            response = client.chat.completions.create(
                model="gpt-4-turbo",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {
                        "role": "user",
                        "content": [
                            {"type": "text", "text": prompt},
                            {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{img_base64}"}}
                        ]
                    }
                ],
                temperature=0.2,
                max_tokens=600
            )

            description = response.choices[0].message.content.strip()

            api_results.append({
                'id': layout['id'],
                'class_name': cls_name,
                'coordinates': [x1, y1, x2, y2],
                'description': description
            })

            logger.info(f"API 응답 완료: ID {layout['id']} - {cls_name}")

        except Exception as e:
            logger.error(f"API 요청 실패: ID {layout['id']} - {e}")

    self.api_results = api_results
    logger.info(f"OpenAI API 처리 완료: {len(api_results)}개 설명 생성")
    return api_results

# 메서드를 클래스에 바인딩
WorksheetAnalyzer.call_openai_api = call_openai_api

print("✅ OpenAI API 메서드 추가 완료!")

# WorksheetAnalyzer 클래스 메서드 추가 (시각화)
def visualize_results(self, image):
    """결과 시각화"""
    img_result = image.copy()
    overlay = image.copy()

    # 클래스별 색상 생성
    random.seed(42)

    unique_classes = list(set(layout['class_name'] for layout in self.layout_info))
    class_colors = {}

    for i, cls_name in enumerate(unique_classes):
        h = i / max(1, len(unique_classes))
        s = 0.8
        v = 0.9
        r, g, b = colorsys.hsv_to_rgb(h, s, v)
        class_colors[cls_name] = (int(b * 255), int(g * 255), int(r * 255))

    # 바운딩 박스 그리기
    for layout in self.layout_info:
        x1, y1, x2, y2 = layout['box']
        cls_name = layout['class_name']
        color = class_colors[cls_name]

        # 반투명 오버레이
        cv2.rectangle(overlay, (x1, y1), (x2, y2), color, -1)

        # 테두리
        cv2.rectangle(img_result, (x1, y1), (x2, y2), color, 2)

        # 라벨
        label = f"{cls_name} ({layout['confidence']:.2f})"
        labelSize, _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 1)
        y1_label = max(y1, labelSize[1] + 10)

        cv2.rectangle(
            img_result,
            (x1, y1_label - labelSize[1] - 10),
            (x1 + labelSize[0], y1_label),
            color,
            -1
        )

        cv2.putText(
            img_result,
            label,
            (x1, y1_label - 5),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.5,
            (255, 255, 255),
            1
        )

    # 반투명 적용
    img_result = cv2.addWeighted(overlay, 0.2, img_result, 0.8, 0)

    return cv2.cvtColor(img_result, cv2.COLOR_BGR2RGB)

def create_text_visualization(self, image):
    """텍스트가 삽입된 문서 시각화"""
    canvas_height, canvas_width = image.shape[:2]
    canvas = np.ones((canvas_height, canvas_width, 3), dtype=np.uint8) * 255

    # OCR 및 API 바운딩 박스 그리기
    for result in self.ocr_results + self.api_results:
        x1, y1, x2, y2 = result['coordinates']
        cv2.rectangle(canvas, (x1, y1), (x2, y2), (0, 0, 0), 2)

    # PIL로 변환하여 한글 텍스트 추가
    canvas_pil = Image.fromarray(cv2.cvtColor(canvas, cv2.COLOR_BGR2RGB))
    draw = ImageDraw.Draw(canvas_pil)

    try:
        font_path = "/usr/share/fonts/truetype/nanum/NanumGothic.ttf"
        font = ImageFont.truetype(font_path, 50)
    except:
        font = ImageFont.load_default()

    # 텍스트 추가
    for result in self.ocr_results:
        x1, y1, x2, y2 = result['coordinates']
        text = result['text'].replace('\n', ' ')
        if len(text) > 50:
            text = text[:50] + "..."
        draw.text((x1 + 5, y1 + 5), text, font=font, fill=(0, 0, 0))

    for result in self.api_results:
        x1, y1, x2, y2 = result['coordinates']
        text = result['description'].replace('\n', ' ')
        if len(text) > 50:
            text = text[:50] + "..."
        draw.text((x1 + 5, y1 + 5), text, font=font, fill=(0, 0, 0))

    return np.array(canvas_pil)

# 메서드를 클래스에 바인딩
WorksheetAnalyzer.visualize_results = visualize_results
WorksheetAnalyzer.create_text_visualization = create_text_visualization

print("✅ 시각화 메서드 추가 완료!")

# WorksheetAnalyzer 클래스 메서드 추가 (JSON 결과 생성)
def get_analysis_json(self):
    """분석 결과를 JSON 형식으로 통합"""
    analysis_data = {
        "layout_analysis": [],
        "ocr_results": [],
        "api_results": []
    }

    # 레이아웃 정보 추가
    for layout in self.layout_info:
        analysis_data["layout_analysis"].append({
            "id": layout['id'],
            "class_name": layout['class_name'],
            "confidence": layout['confidence'],
            "box": layout['box'],
            "width": layout['width'],
            "height": layout['height'],
            "area": layout['area']
        })

    # OCR 결과 추가 (해당 레이아웃 ID와 매핑)
    ocr_dict = {result['id']: result for result in self.ocr_results}
    for layout in self.layout_info:
        if layout['id'] in ocr_dict:
             analysis_data["ocr_results"].append({
                 "layout_id": layout['id'],
                 "class_name": layout['class_name'], # OCR 결과에 클래스명 추가
                 "coordinates": layout['box'], # OCR 결과에 좌표 추가
                 "text": ocr_dict[layout['id']]['text']
             })


    # API 결과 추가 (해당 레이아웃 ID와 매핑)
    api_dict = {result['id']: result for result in self.api_results}
    for layout in self.layout_info:
         if layout['id'] in api_dict:
              analysis_data["api_results"].append({
                  "layout_id": layout['id'],
                  "class_name": layout['class_name'], # API 결과에 클래스명 추가
                  "coordinates": layout['box'], # API 결과에 좌표 추가
                  "description": api_dict[layout['id']]['description']
              })

    # Pretty print JSON
    return json.dumps(analysis_data, indent=4, ensure_ascii=False)

# 메서드를 클래스에 바인딩
WorksheetAnalyzer.get_analysis_json = get_analysis_json

print("✅ JSON 결과 생성 메서드 추가 완료!")

"""## 4. 메인 처리 함수 정의"""

# 기존 process_worksheet 함수를 아래와 같이 수정합니다.

def process_worksheet(image, model_choice, api_key, progress=gr.Progress()):
    """전체 워크시트 처리 파이프라인"""
    if image is None:
        # 이미지 입력이 없으면 빈 결과와 오류 메시지 반환
        return None, None, "이미지를 업로드해주세요.", "", "", None, None # Added None for the file path

    try:
        progress(0.1, desc="모델 다운로드 중...")

        # 모델 다운로드 및 로드
        model_path = analyzer.download_model(model_choice)
        if not analyzer.load_model(model_path):
            # 모델 로드 실패 시 오류 메시지와 빈 결과 반환
            return None, None, "모델 로드에 실패했습니다.", "", "", None, None # Added None for the file path

        progress(0.3, desc="이미지 전처리 및 레이아웃 분석 중...")

        # 이미지 전처리
        if isinstance(image, str):
            img = cv2.imread(image)
        else:
            # PIL 이미지를 OpenCV BGR 형태로 변환
            img = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)

        # 레이아웃 분석
        layout_info = analyzer.analyze_layout(img, model_choice)
        if not layout_info:
            # 레이아웃 분석 결과가 없으면 오류 메시지와 빈 결과 반환
            return cv2.cvtColor(img, cv2.COLOR_BGR2RGB), None, "레이아웃 분석에 실패했습니다. 감지된 요소가 없습니다.", "", "", None, None # Added None for the file path

        progress(0.5, desc="OCR 처리 중...")

        # OCR 처리
        analyzer.perform_ocr(img) # ocr_results는 self에 저장됨

        progress(0.7, desc="AI 설명 생성 중...")

        # OpenAI API 처리
        if api_key and api_key.strip():
             analyzer.call_openai_api(img, api_key) # api_results는 self에 저장됨
        else:
             analyzer.api_results = [] # API 키 없으면 결과 초기화

        progress(0.8, desc="결과 시각화, JSON 생성 중...")

        # 레이아웃 시각화
        layout_viz = analyzer.visualize_results(img)

        # CIM 결과 이미지 시각화 추가
        text_viz = analyzer.create_text_visualization(img)

        # JSON 결과 생성
        json_output_str = analyzer.get_analysis_json()

        # JSON 문자열을 파일로 저장 (Gradio File 컴포넌트 출력을 위해)
        json_filepath = "./analysis_result.json"
        with open(json_filepath, "w", encoding='utf-8') as f:
             f.write(json_output_str)


        # 통계 생성 (기존 로직 유지)
        stats = f"""📊 분석 결과 통계:
• 총 감지된 레이아웃 요소: {len(layout_info)}개
• OCR 처리된 텍스트 블록: {len(analyzer.ocr_results)}개
• AI 설명 생성된 이미지/표: {len(analyzer.api_results)}개

📋 감지된 레이아웃 클래스:
"""

        class_counts = Counter(item['class_name'] for item in layout_info)
        for cls, count in class_counts.items():
            stats += f"• {cls}: {count}개\n"

        # OCR 결과 텍스트 (기존 로직 유지)
        ocr_text = "📝 추출된 텍스트:\n\n"
        if analyzer.ocr_results:
            for i, result in enumerate(analyzer.ocr_results):
                preview = result['text'][:100].replace('\n', ' ') + "..." if len(result['text']) > 100 else result['text'].replace('\n', ' ')
                ocr_text += f"[{i+1}] {result['class_name']}: {preview}\n\n"
        else:
             ocr_text += "추출된 텍스트가 없습니다.\n\n"


        # AI 설명 텍스트 (기존 로직 유지)
        ai_text = "🤖 AI 생성 설명:\n\n"
        if analyzer.api_results:
            for i, result in enumerate(analyzer.api_results):
                preview = result['description'][:200].replace('\n', ' ') + "..." if len(result['description']) > 200 else result['description'].replace('\n', ' ')
                ai_text += f"[{i+1}] {result['class_name']}: {preview}\n\n"
        else:
             ai_text += "AI 설명이 생성되지 않았습니다 (API 키 확인).\n\n"


        progress(1.0, desc="완료!")

        # 레이아웃 시각화 이미지, CIM 시각화 이미지, 통계 문자열, OCR 텍스트, AI 설명 텍스트, JSON 파일 경로 반환
        return layout_viz, text_viz, stats, ocr_text, ai_text, json_filepath

    except Exception as e:
        logger.error(f"처리 중 오류 발생: {e}")
        # Ensure all 6 outputs are returned even on error
        return None, None, f"오류가 발생했습니다: {str(e)}", "", "", None

print("✅ 메인 처리 함수 수정 완료 (CIM 시각화, JSON 파일 저장 및 반환)!")

# 분석기 인스턴스 생성
analyzer = WorksheetAnalyzer()

# 기존의 5개 출력을 반환하는 process_worksheet 함수 정의를 삭제합니다.
# def process_worksheet(image, model_choice, api_key, progress=gr.Progress()):
#     """전체 워크시트 처리 파이프라인"""
#     if image is None:
#         return None, None, "이미지를 업로드해주세요.", "", ""

#     try:
#         progress(0.1, desc="모델 다운로드 중...")

#         # 모델 다운로드 및 로드
#         model_path = analyzer.download_model(model_choice)
#         if not analyzer.load_model(model_path):
#             return None, None, "모델 로드에 실패했습니다.", "", ""

#         progress(0.3, desc="레이아웃 분석 중...")

#         # 이미지 전처리
#         if isinstance(image, str):
#             img = cv2.imread(image)
#         else:
#             img = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)

#         # 레이아웃 분석
#         layout_info = analyzer.analyze_layout(img, model_choice)
#         if not layout_info:
#             return None, None, "레이아웃 분석에 실패했습니다.", "", ""

#         progress(0.5, desc="OCR 처리 중...")

#         # OCR 처리
#         ocr_results = analyzer.perform_ocr(img)

#         progress(0.7, desc="AI 설명 생성 중...")

#         # OpenAI API 처리
#         api_results = []
#         if api_key and api_key.strip():
#             api_results = analyzer.call_openai_api(img, api_key)

#         progress(0.9, desc="결과 시각화 중...")

#         # 결과 시각화
#         layout_viz = analyzer.visualize_results(img)
#         text_viz = analyzer.create_text_visualization(img)

#         # 통계 생성
#         stats = f"""📊 분석 결과 통계:
# • 총 감지된 레이아웃 요소: {len(layout_info)}개
# • OCR 처리된 텍스트 블록: {len(ocr_results)}개
# • AI 설명 생성된 이미지/표: {len(api_results)}개

# 📋 감지된 레이아웃 클래스:
# """

#         class_counts = Counter(item['class_name'] for item in layout_info)
#         for cls, count in class_counts.items():
#             stats += f"• {cls}: {count}개\n"

#         # OCR 결과 텍스트
#         ocr_text = "📝 추출된 텍스트:\n\n"
#         for i, result in enumerate(ocr_results):
#             preview = result['text'][:100] + "..." if len(result['text']) > 100 else result['text']
#             ocr_text += f"[{i+1}] {result['class_name']}: {preview}\n\n"

#         # AI 설명 텍스트
#         ai_text = "🤖 AI 생성 설명:\n\n"
#         for i, result in enumerate(api_results):
#             preview = result['description'][:200] + "..." if len(result['description']) > 200 else result['description']
#             ai_text += f"[{i+1}] {result['class_name']}: {preview}\n\n"

#         progress(1.0, desc="완료!")

#         return layout_viz, text_viz, stats, ocr_text, ai_text

#     except Exception as e:
#         logger.error(f"처리 중 오류 발생: {e}")
#         return None, None, f"오류가 발생했습니다: {str(e)}", "", ""

print("✅ 메인 처리 함수 정의 (수정된 버전 사용)!")

"""## 5. Gradio 인터페이스 생성"""

# 기존 create_demo 함수를 아래와 같이 수정합니다.

def create_demo():
    with gr.Blocks(title="📚 학습지 분석 시스템", theme=gr.themes.Soft()) as demo:
        gr.Markdown("""
        # 📚 학습지 분석 시스템 (LAM + TSPM + CIM + JSON)

        **시각 장애 아동을 위한 AI 기반 학습지 분석 및 텍스트 변환 시스템**

        이 시스템은 학습지 이미지를 분석하여 레이아웃을 파악하고, 텍스트를 추출하며,
        그림과 표에 대한 상세한 설명을 생성합니다. 결과는 시각화 이미지와 JSON 파일로 제공됩니다.
        """)

        with gr.Row():
            with gr.Column(scale=1):
                gr.Markdown("### 📋 입력 설정")

                image_input = gr.Image(
                    label="학습지 이미지 업로드",
                    type="pil",
                    height=400,
                    width=1500
                )

                model_choice = gr.Radio(
                    choices=[
                        ("DocStructBench (학습지 최적화)", "docstructbench"),
                        ("DocLayNet-Docsynth300K (일반문서)", "doclaynet_docsynth"),
                        ("DocSynth300K (사전훈련모델)", "docsynth300k"),
                        ("SmartEyeSsen (학습지 파인튜닝)", "SmartEyeSsen"),
                    ],
                    label="분석 모델 선택",
                    value="docstructbench"
                )

                api_key = gr.Textbox(
                    label="OpenAI API Key (선택사항)",
                    type="password",
                    placeholder="sk-...",
                    info="그림과 표에 대한 AI 설명 생성용"
                )

                analyze_btn = gr.Button(
                    "🚀 분석 시작",
                    variant="primary",
                    size="lg"
                )

            with gr.Column(scale=2):
                gr.Markdown("### 📊 분석 결과")

                with gr.Tabs():
                    with gr.TabItem("🎯 레이아웃 분석 시각화"):
                        layout_result = gr.Image(
                            label="레이아웃 분석 결과 이미지",
                            height=400,
                            width=1500,
                            interactive=False
                        )

                    with gr.TabItem("📄 CIM 결과 시각화"): # 탭 이름 수정
                        text_result = gr.Image(
                            label="CIM 변환 결과 이미지 (텍스트/설명)",
                            height=400,
                            width=1500,
                            interactive=False
                        )

                    with gr.TabItem("📊 전체 분석 결과 (JSON)"): # JSON 탭 추가
                         json_file_output = gr.File(
                             label="분석 결과 JSON 파일",
                             file_count="single",
                             type="filepath",
                             interactive=False
                         )
                         gr.Markdown("분석 완료 후 위 링크에서 JSON 파일을 다운로드할 수 있습니다.")


        with gr.Row():
            with gr.Column():
                stats_output = gr.Textbox(
                    label="📊 분석 통계",
                    lines=10,
                    max_lines=15,
                    interactive=False
                )

            with gr.Column():
                with gr.Accordion("📝 OCR 추출 텍스트", open=False):
                    ocr_output = gr.Textbox(
                        label="추출된 텍스트",
                        lines=8,
                        max_lines=12,
                        interactive=False
                    )

                with gr.Accordion("🤖 표/그림 AI 생성 설명", open=False):
                    ai_output = gr.Textbox(
                        label="AI 설명",
                        lines=8,
                        max_lines=12,
                        interactive=False
                    )

        gr.Markdown("""
        ---
        ### 📋 사용 방법
        1. **이미지 업로드**: 분석할 학습지 이미지를 업로드하세요
        2. **모델 선택**: 학습지 분석에는 'DocStructBench' 모델을 권장합니다
        3. **API 키 입력**: 그림/표 설명 생성을 위해 OpenAI API 키를 입력하세요 (선택사항)
        4. **분석 시작**: '🚀 분석 시작' 버튼을 클릭하여 처리를 시작하세요
        5. **결과 확인**: '레이아웃 분석 시각화', 'CIM 결과 시각화' 탭에서 이미지 결과를 확인하고, '전체 분석 결과 (JSON)' 탭에서 JSON 파일을 다운로드하세요.

        ### 🔧 기술 스택
        - **LAM**: DocLayout-YOLO를 사용한 레이아웃 분석
        - **TSPM**: Tesseract OCR + OpenAI GPT-4V를 사용한 텍스트 및 이미지 처리
        - **CIM**: 결과 통합 및 시각화, JSON 변환
        """)

        # 이벤트 바인딩: 출력 파라미터 순서에 유의하여 업데이트
        analyze_btn.click(
            fn=process_worksheet,
            inputs=[image_input, model_choice, api_key],
            outputs=[layout_result, text_result, stats_output, ocr_output, ai_output, json_file_output], # 출력 컴포넌트 순서 매칭
            show_progress=True
        )

    return demo

print("✅ Gradio 인터페이스 수정 완료 (CIM 이미지 및 JSON 다운로드 모두 포함)!")

# 데모 생성 및 실행 (이 부분은 기존과 동일)
print("🚀 Gradio 데모를 시작합니다...")

demo = create_demo()

# Colab에서 실행
demo.launch(
    server_name="0.0.0.0",  # Colab에서 외부 접근 허용
    server_port=7860,
    share=True,  # 공개 링크 생성
    debug=True,
    show_error=True
)

print("✅ 데모가 성공적으로 시작되었습니다!")
print("📱 위의 링크를 클릭하여 데모에 접속하세요.")

"""## 6. 데모 실행

## 📝 사용 참고사항

### 🔧 **시스템 요구사항**
- **GPU**: CUDA 지원 GPU 권장 (CPU도 가능하지만 느림)
- **메모리**: 최소 4GB RAM
- **인터넷**: 모델 다운로드 및 OpenAI API 호출용

### 📊 **지원하는 분석 요소**
- **레이아웃 분석**: title, text, figure, table, formula 등
- **OCR 처리**: 한국어/영어 혼합 텍스트
- **AI 설명**: 그림과 표에 대한 상세 설명

### ⚠️ **주의사항**
1. **OpenAI API 키**는 그림/표 설명 생성에만 필요 (선택사항)
2. **첫 실행 시** 모델 다운로드로 인해 시간이 소요될 수 있음
3. **이미지 크기**가 클수록 처리 시간이 길어짐
4. **학습지 품질**이 좋을수록 분석 정확도가 높아짐

### 🎯 **최적 사용법**
- **선명한 스캔본** 또는 **고해상도 사진** 사용
- **DocStructBench 모델** 권장 (학습지에 최적화)
- **API 키 입력** 시 더 풍부한 설명 제공
"""