# Generated by Django 4.2.7 on 2025-08-10 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100, verbose_name='작업명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소됨')], default='pending', max_length=20, verbose_name='상태')),
                ('model_type', models.CharField(choices=[('docstructbench', 'DocStructBench'), ('doclaynet_docsynth', 'DocLayNet DocSynth'), ('docsynth300k', 'DocSynth300K')], max_length=50, verbose_name='모델 유형')),
                ('processing_mode', models.CharField(choices=[('basic', '기본'), ('advanced', '고급')], default='basic', max_length=20, verbose_name='처리 모드')),
                ('total_images', models.IntegerField(verbose_name='총 이미지 수')),
                ('processed_images', models.IntegerField(default=0, verbose_name='처리된 이미지 수')),
                ('failed_images', models.IntegerField(default=0, verbose_name='실패한 이미지 수')),
                ('batch_size', models.IntegerField(default=2, verbose_name='배치 크기')),
                ('enable_resume', models.BooleanField(default=True, verbose_name='재시작 활성화')),
                ('enable_ocr', models.BooleanField(default=True, verbose_name='OCR 활성화')),
                ('enable_api', models.BooleanField(default=True, verbose_name='API 활성화')),
                ('priority', models.IntegerField(default=0, verbose_name='우선순위')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('estimated_completion', models.DateTimeField(blank=True, null=True, verbose_name='예상 완료일시')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '분석 작업',
                'verbose_name_plural': '분석 작업들',
                'db_table': 'analysis_jobs',
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('complete', '완전 분석'), ('lam_only', 'LAM만'), ('tspm_only', 'TSPM만'), ('cim_only', 'CIM만')], default='complete', max_length=20, verbose_name='결과 유형')),
                ('result_data', models.JSONField(default=dict, verbose_name='결과 데이터')),
                ('processing_time', models.FloatField(default=0.0, verbose_name='처리 시간 (초)')),
                ('detection_count', models.IntegerField(default=0, verbose_name='탐지된 요소 수')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='평균 신뢰도 점수')),
                ('file_paths', models.JSONField(default=dict, verbose_name='생성된 파일 경로들')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '분석 결과',
                'verbose_name_plural': '분석 결과들',
                'db_table': 'analysis_results',
            },
        ),
        migrations.CreateModel(
            name='CIMIntegratedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integrated_data', models.JSONField(default=dict, verbose_name='통합 데이터')),
                ('visualization_paths', models.JSONField(default=dict, verbose_name='시각화 파일 경로들')),
                ('summary_stats', models.JSONField(default=dict, verbose_name='요약 통계')),
                ('export_formats', models.JSONField(default=dict, verbose_name='내보내기 형식들')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': 'CIM 통합 결과',
                'verbose_name_plural': 'CIM 통합 결과들',
                'db_table': 'cim_integrated_results',
            },
        ),
        migrations.CreateModel(
            name='CIMOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_text', models.TextField(verbose_name='최종 텍스트')),
                ('braille_notation', models.TextField(blank=True, verbose_name='점자 표기')),
                ('reading_order', models.JSONField(default=dict, verbose_name='읽기 순서')),
                ('export_format', models.CharField(choices=[('text', '텍스트'), ('json', 'JSON'), ('xml', 'XML'), ('braille', '점자')], default='text', max_length=20, verbose_name='출력 형식')),
                ('accessibility_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='접근성 점수')),
                ('word_count', models.IntegerField(blank=True, null=True, verbose_name='단어 수')),
                ('estimated_reading_time', models.IntegerField(blank=True, null=True, verbose_name='예상 읽기 시간 (분)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': 'CIM 출력',
                'verbose_name_plural': 'CIM 출력들',
                'db_table': 'cim_outputs',
            },
        ),
        migrations.CreateModel(
            name='DocumentStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_type', models.CharField(max_length=50, verbose_name='구조 유형')),
                ('page_layout', models.JSONField(default=dict, verbose_name='페이지 레이아웃')),
                ('content_hierarchy', models.JSONField(default=dict, verbose_name='내용 계층 구조')),
                ('reading_flow', models.JSONField(default=dict, verbose_name='읽기 흐름')),
                ('difficulty_level', models.CharField(blank=True, choices=[('elementary', '초등'), ('middle', '중등'), ('high', '고등')], max_length=20, null=True, verbose_name='난이도')),
                ('subject_area', models.CharField(blank=True, max_length=50, verbose_name='과목 영역')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '문서 구조',
                'verbose_name_plural': '문서 구조들',
                'db_table': 'document_structure',
            },
        ),
        migrations.CreateModel(
            name='LAMLayoutDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_order', models.IntegerField(verbose_name='감지 순서')),
                ('class_name', models.CharField(max_length=50, verbose_name='클래스명')),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='신뢰도')),
                ('bbox_x1', models.IntegerField(verbose_name='바운딩박스 X1')),
                ('bbox_y1', models.IntegerField(verbose_name='바운딩박스 Y1')),
                ('bbox_x2', models.IntegerField(verbose_name='바운딩박스 X2')),
                ('bbox_y2', models.IntegerField(verbose_name='바운딩박스 Y2')),
                ('area_pixels', models.IntegerField(verbose_name='영역 픽셀 수')),
                ('width_ratio', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='너비 비율')),
                ('height_ratio', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='높이 비율')),
                ('center_x', models.IntegerField(verbose_name='중심 X')),
                ('center_y', models.IntegerField(verbose_name='중심 Y')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': 'LAM 레이아웃 감지',
                'verbose_name_plural': 'LAM 레이아웃 감지들',
                'db_table': 'lam_layout_detections',
            },
        ),
        migrations.CreateModel(
            name='TSPMOCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(verbose_name='추출된 텍스트')),
                ('processed_text', models.TextField(blank=True, verbose_name='처리된 텍스트')),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='신뢰도')),
                ('language', models.CharField(default='kor', max_length=10, verbose_name='언어')),
                ('processing_method', models.CharField(default='tesseract', max_length=50, verbose_name='처리 방법')),
                ('text_length', models.IntegerField(verbose_name='텍스트 길이')),
                ('processing_time_ms', models.IntegerField(blank=True, null=True, verbose_name='처리 시간 (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='analysis.lamlayoutdetection', verbose_name='감지 결과')),
            ],
            options={
                'verbose_name': 'TSPM OCR 결과',
                'verbose_name_plural': 'TSPM OCR 결과들',
                'db_table': 'tspm_ocr_results',
            },
        ),
        migrations.CreateModel(
            name='TSPMImageDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.TextField(verbose_name='설명 텍스트')),
                ('subject_category', models.CharField(blank=True, max_length=50, verbose_name='주제 카테고리')),
                ('description_type', models.CharField(blank=True, max_length=50, verbose_name='설명 유형')),
                ('api_model', models.CharField(default='gpt-4-turbo', max_length=50, verbose_name='API 모델')),
                ('api_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='API 비용')),
                ('processing_time_ms', models.IntegerField(blank=True, null=True, verbose_name='처리 시간 (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_descriptions', to='analysis.lamlayoutdetection', verbose_name='감지 결과')),
            ],
            options={
                'verbose_name': 'TSPM 이미지 설명',
                'verbose_name_plural': 'TSPM 이미지 설명들',
                'db_table': 'tspm_image_descriptions',
            },
        ),
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_filename', models.CharField(max_length=255, verbose_name='처리된 파일명')),
                ('page_number', models.IntegerField(default=1, verbose_name='페이지 번호')),
                ('image_width', models.IntegerField(verbose_name='이미지 너비')),
                ('image_height', models.IntegerField(verbose_name='이미지 높이')),
                ('processing_status', models.CharField(choices=[('pending', '대기중'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('processing_time_ms', models.IntegerField(blank=True, null=True, verbose_name='처리 시간 (ms)')),
                ('memory_usage_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='메모리 사용량 (MB)')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_image_set', to='analysis.analysisjob', verbose_name='분석 작업')),
            ],
            options={
                'verbose_name': '처리된 이미지',
                'verbose_name_plural': '처리된 이미지들',
                'db_table': 'processed_images',
            },
        ),
    ]
