# Generated by Django 4.2.7 on 2025-08-10 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimage',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_images', to='files.sourcefile', verbose_name='원본 파일'),
        ),
        migrations.AddField(
            model_name='lamlayoutdetection',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_detections', to='analysis.processedimage', verbose_name='이미지'),
        ),
        migrations.AddField(
            model_name='documentstructure',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_structures', to='analysis.analysisjob', verbose_name='분석 작업'),
        ),
        migrations.AddField(
            model_name='cimoutput',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cim_outputs', to='analysis.analysisjob', verbose_name='분석 작업'),
        ),
        migrations.AddField(
            model_name='cimintegratedresult',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cim_integrated_results', to='analysis.analysisjob', verbose_name='분석 작업'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.analysisjob', verbose_name='분석 작업'),
        ),
    ]
