# Generated by Django 4.2.7 on 2025-08-10 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='tspmocrresult',
            index=models.Index(fields=['detection'], name='tspm_ocr_re_detecti_23349e_idx'),
        ),
        migrations.AddIndex(
            model_name='tspmimagedescription',
            index=models.Index(fields=['detection'], name='tspm_image__detecti_13cff1_idx'),
        ),
        migrations.AddIndex(
            model_name='tspmimagedescription',
            index=models.Index(fields=['subject_category', 'description_type'], name='tspm_image__subject_a2aece_idx'),
        ),
        migrations.AddIndex(
            model_name='processedimage',
            index=models.Index(fields=['job', 'processing_status'], name='processed_i_job_id_5d7670_idx'),
        ),
        migrations.AddIndex(
            model_name='processedimage',
            index=models.Index(fields=['source_file', 'page_number'], name='processed_i_source__5f734e_idx'),
        ),
        migrations.AddIndex(
            model_name='lamlayoutdetection',
            index=models.Index(fields=['image', 'detection_order'], name='lam_layout__image_i_11bc93_idx'),
        ),
        migrations.AddIndex(
            model_name='lamlayoutdetection',
            index=models.Index(fields=['class_name', 'confidence'], name='lam_layout__class_n_c0ebae_idx'),
        ),
        migrations.AddIndex(
            model_name='documentstructure',
            index=models.Index(fields=['job'], name='document_st_job_id_9220cc_idx'),
        ),
        migrations.AddIndex(
            model_name='documentstructure',
            index=models.Index(fields=['subject_area', 'difficulty_level'], name='document_st_subject_b551d1_idx'),
        ),
        migrations.AddIndex(
            model_name='cimoutput',
            index=models.Index(fields=['job'], name='cim_outputs_job_id_ee55cd_idx'),
        ),
        migrations.AddIndex(
            model_name='cimintegratedresult',
            index=models.Index(fields=['job'], name='cim_integra_job_id_3c4971_idx'),
        ),
        migrations.AddIndex(
            model_name='cimintegratedresult',
            index=models.Index(fields=['created_at'], name='cim_integra_created_23d1b8_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['job'], name='analysis_re_job_id_f1a745_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['result_type'], name='analysis_re_result__45940f_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['created_at'], name='analysis_re_created_2bdd23_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['user', 'status', 'created_at'], name='analysis_jo_user_id_d8c5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='analysis_jo_status_79cd01_idx'),
        ),
    ]
